(function(){
  window.OCContent = {
    "mortgage": [
      { tag: "h1", text: "The Mortgage Calculator gives you a rough idea of what you'll pay each month for your mortgage, plus any other related expenses" },
      { tag: "h2", text: "You can opt for extra payments or annual hikes in typical home loan costs" },
      { tag: "p", text: "The calculator's primary purpose is for people living in the U.S" },

      { tag: "h3", text: "Mortgages" },
      { tag: "p", text: "A mortgage is basically a loan that's backed up by property, typically a house or land. Lenders call it the cash you get to buy property. Basically, the bank assists the homebuyer in covering the seller's house cost, and the buyer commits to paying back the loan over a typical span of 15 or 30 years here in the States. Every month, the buyer sends money to the lender. A segment of the monthly payment is referred to as the principal, which is the initial sum borrowed. The other part is the interest, which is the fee you pay the lender for borrowing their cash. There might be an escrow account set up to handle the property taxes and insurance expenses. The buyer isn't the full owner of the mortgaged property until they've made the final monthly payment. In the U.S., the go-to mortgage is the standard 30-year fixed-rate deal, making up about 70% to 90% of all home loans. Most people in the U.S. get their homes through mortgages." },

      { tag: "h3", text: "Mortgage Calculator Components" },
      { tag: "p", text: "A mortgage typically has these main parts. These are also the key elements of a mortgage calculator." },
      { tag: "p", html: "The loan amount is the sum of money you get from a lender or bank. In a mortgage, this is basically the price you pay minus what you put down upfront. The usual loan amount you can get usually matches up with how much you earn or what you can afford. <strong>Estimate a budget-friendly figure</strong> just hit up our House Affordability Calculator." },
      { tag: "p", text: "A down payment is the initial cash you put down when buying something, typically a slice of the total cost. This part of the price the borrower pays upfront. Usually, banks or mortgage companies prefer you to pay at least 20% of the home's price upfront. Sometimes, people can put down as little as 3%. If borrowers put down less than 20% of the home's price, they'll have to pay for private mortgage insurance. Borrowers must maintain this insurance until the loan's remaining principal falls beneath 80% of the home's initial purchase price. A good rule of thumb is that when you put down a bigger down payment, you're more likely to get a better interest rate and your loan application has a better shot at getting approved." },
      { tag: "p", text: "The loan term is basically how long you've got to pay back the whole loan. Most fixed-rate mortgages are typically set for 15, 20, or 30 years. A shorter time frame, like 15 or 20 years, usually means a lower interest rate." },
      { tag: "p", text: "The interest rate represents the expense of borrowing funds, shown as a percentage of the loan amount. Mortgages offer you two types: fixed-rate mortgages (FRM) or adjustable-rate mortgages (ARM). Interest rates stay constant throughout the fixed-rate mortgage term. The calculator up there does just fixed rates. For ARMs, the interest rates are usually set for a while, and then they'll get adjusted regularly depending on market trends. Borrowers get a bit of the risk off their shoulders when ARMs are involved. So, usually, the starting interest rates are about half a percent to two percent less than those fixed-rate mortgages with the same loan period. Mortgage interest rates are usually shown as the Annual Percentage Rate (APR), sometimes also known as nominal APR or effective APR. The interest rate is basically the yearly rate, but you break it down into how often it compounds in a year. So, if you've got a mortgage rate at 6% APR, that's like saying you'll be shelling out 0.5% in interest each month." },

      { tag: "h3", text: "Costs Associated with Home Ownership and Mortgages" },
      { tag: "p", text: "Monthly mortgage payments typically make up most of the money you spend on owning a house, but don't forget about other big expenses. These expenses are split into two groups: ongoing and one-time." },

      { tag: "h3", text: "Recurring Costs" },
      { tag: "p", text: "Most ongoing expenses stick around even after the mortgage is paid off. They play a big role in finances. Property taxes, home insurance, HOA fees, and other expenses tend to go up over time because of inflation. In the calculator, the recurring expenses are listed under the Include Options below checkbox. Optional inputs in the calculator for yearly growth rates are available under More Options. They can help you get more precise results." },
      { tag: "p", text: "Property taxes are the fees homeowners shell out to local government bodies. In the U.S., local city or county authorities typically handle property taxes. Every state has its own local taxes on property. The U.S. sees different real estate taxes depending on where you are; generally, people shell out around 1.1% of their home's worth in property taxes annually." },
      { tag: "p", text: "Home insurance is a policy that safeguards the owner against accidents affecting their actual property. Home insurance might also include personal liability coverage, which guards you against lawsuits if someone gets hurt on or off your property. Home insurance prices change based on where you live, how well your place is kept, and how much protection you want." },
      { tag: "p", text: "Private mortgage insurance (PMI) is there to cover the lender if the borrower can't pay back the loan. In the U.S., if you put down less than 20% on a house, the bank usually asks you to pay for private mortgage insurance until your loan amount is 80% or 78% of the house's value. PMI costs fluctuate based on elements like the down payment, loan amount, and borrower's credit. The usual yearly cost usually sits between 0.3% and 1.9% of the loan's total amount." },
      { tag: "p", text: "The HOA fee is what the property owner pays to the homeowner's association, which is a group that takes care of and enhances the neighborhood's properties and surroundings. Condos, townhomes, and a few houses with just one family often need people to chip in for HOA fees. Annual HOA fees typically don't exceed a tenth of your home's worth." },

      { tag: "p", html: "<strong>Other costs</strong> like electricity, fixing up the place, and general home-keeping stuff. It's pretty usual to shell out at least 1% or more of your home's value just for yearly upkeep." },

      { tag: "h3", text: "Non-Recurring Costs" },
      { tag: "p", text: "These expenses aren't on the calculator's radar, but they're still key to remember. Closing costs are the fees you pay when finalizing a property deal. These aren't regular charges, but they can still hit your wallet hard. In the U.S., when you're buying a house, you've gotta pay a bunch of extra costs on top of the mortgage. This includes lawyer fees, the cost for checking the title, recording fees, survey fees, taxes for transferring the property, bro." },
      { tag: "p", text: "These costs usually hit the buyer, but you can sometimes work out a credit deal with the seller or the lender. It's pretty common for someone buying a $400,000 house to shell out around $10,000 in closing costs." },
      { tag: "p", text: "Some people opt to spruce up the place before they even move in. Renovations can mean swapping out the floors, giving the walls a fresh coat of paint, sprucing up the kitchen, or totally revamping the inside or outside. Renovation costs can pile up fast, but it's not a must for owners to tackle those fixes right away." },
      { tag: "p", text: "When you buy a house, you usually have to shell out extra for things like new furniture, appliances, and the hassle of moving. This covers repair expenses too." },

      { tag: "h3", text: "Early Repayment and Extra Payments" },
      { tag: "p", text: "A lot of people who've taken out a mortgage might think about paying it off sooner rather than later, maybe all at once or just a bit at a time. They might do this to save on interest, to sell their house, or to refinance. Our calculator can handle monthly, yearly, or one-off additional payments. But, people gotta get the lowdown on the good and bad of paying extra on their home loan." },

      { tag: "h3", text: "Early Repayment Strategies" },
      { tag: "p", text: "Besides wiping out the mortgage loan in full, usually, there are three key ways to pay off your mortgage loan sooner. People mainly use these tactics to cut down on interest costs. These methods can be applied separately or together." },
      { tag: "p", html: "<strong>Making additional payments</strong> It's just paying more than your regular monthly amount. On regular long-term mortgages, most of the first payments are actually going towards interest instead of reducing the actual loan amount. Extra payments will knock down the loan balance, which means less interest and helps the borrower get out of debt sooner. Some people get into the routine of tipping over the odds each month, but others just throw in a few extra whenever they feel like it. Optional inputs in the Mortgage Calculator let you add extra payments, and it's pretty handy to see how your mortgage stacks up with or without those extra payments." },
      { tag: "p", text: "Every two weeks, the borrower makes a payment that's half of what they'd normally pay each month. In a year with 52 weeks, that's like making 26 payments or 13 months' worth of mortgage payments. This approach is mainly for people who get paid every two weeks. It's simpler for them to get into the habit of setting aside a bit from each paycheck for their mortgage. Showcased in the computed figures are biweekly payments for comparison." },
      { tag: "p", html: "<strong>Switching to a shorter-term loan</strong> it's like getting a fresh loan to pay off the old one. By using this approach, borrowers can reduce the loan period, usually leading to a smaller interest charge. This can help you get your money back faster and save on interest costs, but usually means you've gotta pay more each month. A borrower might have to shell out for closing costs and fees when they refinance." },

      { tag: "h3", text: "Reasons for early repayment" },
      { tag: "p", html: "<strong>Lower interest costs</strong> Borrowers can save a bunch of cash on interest, which usually ends up being a big chunk of their expenses." },
      { tag: "p", html: "<strong>Reduced repayment duration</strong> A decreased repayment duration indicates that the payoff will occur more quickly than the initial term outlined in the mortgage contract. This means the person who borrowed the money pays it back quicker." },
      { tag: "p", html: "<strong>Feeling good about yourself</strong> that sense of happiness and peace you get when you're not weighed down by debt. Being debt-free gives people the freedom to spend and invest in other stuff." },

      { tag: "h3", text: "Drawbacks of early repayment" },
      { tag: "p", text: "Nonetheless, additional payments also incur expenses. Borrowers should think about these things before paying extra on their mortgage." },
      { tag: "p", html: "<strong>Potential prepayment fees</strong> A prepayment fee is a provision, typically detailed in a mortgage agreement, between a borrower and a mortgage lender that outlines what the borrower may do to pay off and when. Penalty fees typically show up as a percentage of what you owe when you pay off early, or as a set number of months' worth of interest. The fine usually drops over time until it eventually disappears, usually within about 5 years. Normally, if you sell your home, you don't have to pay a prepayment penalty for that one-time payment." },
      { tag: "p", text: "Sometimes, it might not make sense to pay off your mortgage early because the interest rates are pretty low compared to other investments. So, if you're paying off a house loan at 4% interest, but you could be making 10% or more by investing that cash, you're missing out on a pretty big opportunity cost." },
      { tag: "p", html: "<strong>Money tied up in the house</strong> It's cash that the borrower can't use for anything else. This could end up making someone borrow more money if they suddenly need cash." },

      { tag: "h3", text: "Concise Overview of Mortgages in the U.S." },
      { tag: "p", text: "In the early 1900s, purchasing a home required saving a substantial amount for the down payment. Individuals had to contribute half of the total cost, secure a loan for three to five years, and face a large payment upon maturity. Under these conditions, only four of ten Americans were able to buy a home. During the Great Depression, one in four homeowners lost their properties." },

      { tag: "p", text: "To address this, the government established the Federal Housing Administration and Fannie Mae in the 1930s to enhance the mortgage market's liquidity, stability, and affordability. Both organizations contributed to the introduction of 30-year mortgages with lower down payments and standardized construction practices." },
      { tag: "p", text: "These initiatives also assisted returning veterans in funding a house after World War II concluded and initiated a construction surge in the subsequent decades. The FHA intervened to help borrowers during challenging periods, such as the inflation issues of the '70s and the drop in energy prices in the '80s." }
    ],
    "compound-interest": [
      { tag: "h1", text: "Calculating Compound Interest" },
      { tag: "p", text: "Written by: Fawad Khan" },
      { tag: "p", text: "To figure out what money will be worth later with compound interest, start with how much you have now. That sum joins a set interest percentage, applied repeatedly across spans of time. As each interval passes, growth builds on earlier gains. This process uses today's deposit as its base point. Growth multiplies step by step through each phase it moves. See the equation laid out here next." },
      { tag: "h3", text: "Where:" },
      { tag: "p", html: "<ul><li><strong>FV</strong> = Future Value</li><li><strong>PV</strong> = Present Value (what you have now)</li><li><strong>i</strong> = periodic interest rate</li><li><strong>n</strong> = number of compounding periods</li></ul>" },
      { tag: "p", text: "Right now, what you put into the account counts as the starting sum. For each stretch of time, there’s a set percentage gain, call it i. Then n stands for how many times that growth repeats. You could apply this math whether gains stack once per year, every month, or any other span. One detail matters above all: line up the rate with the timing. Say days, that means using a daily figure for interest. Think months? Pull out the monthly version instead. Here comes a real case to show how it works." },
      { tag: "p", text: "Imagine putting a thousand dollars into a bank account earning four percent each year. What happens after five years shows how compound growth works. With yearly compounding, earnings get added back into the total. That means next year's gain builds on last year's profit too. Over time, even small sums grow because gains generate their own gains. The original amount grows without extra deposits simply by staying in place. That is where things multiply fast. Take a moment to see how the math works out." },
      { tag: "p", text: "Start off just like a basic interest math problem. Instead of taking the money you made and walking away, put it back into the account. One year passes, and now there is $1,040 sitting in the bank, thanks to $40 added from 4% of $1,000. This time around, let that sum stay. By year two, growth builds on top of that full $1,040 balance at the same 4% rate. After two years, the total becomes $1,081.60, starting from $1,040 growing by 4%. That second year brings in $41.60 extra, since the gain applies to last year's full amount. Gains build on prior gains, instead of repeating the same fixed addition yearly. Running this forward across five years reveals how it unfolds. A visual breakdown appears just beneath this line." },
      { tag: "div", html: "<div class='panel'><table class='schedule-table'><thead><tr><th>Year</th><th>PV</th><th>Interest</th><th>FV</th></tr></thead><tbody><tr><td>1</td><td>$1,000.00</td><td>$40.00</td><td>$1,040.00</td></tr><tr><td>2</td><td>$1,040.00</td><td>$41.60</td><td>$1,081.60</td></tr><tr><td>3</td><td>$1,081.60</td><td>$43.26</td><td>$1,124.86</td></tr><tr><td>4</td><td>$1,124.86</td><td>$45.00</td><td>$1,169.86</td></tr><tr><td>5</td><td>$1,169.86</td><td>$46.79</td><td>$1,216.65</td></tr></tbody></table></div>" },
      { tag: "p", text: "Look at how the interest grows every year because the starting balance climbs. Five years pass, then there is $1,216.65 sitting in the account. That total comes from piling up all the yearly interest, found in the Interest column, and tacking it onto the original deposit. Sure, working this out by hand feels messy, step after step just to know what $1,000 becomes down the road. Yet, luckily, a ready-made equation does the heavy lifting. Using the formula shown next makes finding tomorrow's value straightforward." },
      { tag: "p", text: "That formula gives us the amount later on, but getting just the interest part takes a tiny extra move. Take away today's number from that result since what grows includes what you started with along with added gain. Here, the extra gained comes out to two hundred sixteen dollars and sixty-five cents, adding up every yearly increase once more." },
      { tag: "h3", text: "When timing and rate differ" },
      { tag: "p", text: "Keep in mind, we used the annual rate straight away since compounding happened once per year. Now imagine the interest rate doesn’t match how often it compounds." },
      { tag: "p", text: "When bases differ during compounding, adjustments matter. This calculation works across durations, no fixed timeline needed. Still, match the rate to its period type. Each growth step needs alignment between timing and percentage gain." },
      { tag: "p", text: "Take earlier numbers: switching annual gains to every six months shifts things. Now consider n and i values under new rhythm. Since n counts total intervals, splitting yearly into halves doubles it. Five years times two splits gives ten steps. Frequency shapes count; twice each year means more cycles within the same span." },
      { tag: "p", text: "Right now, using the old interest number won’t work, imagine having n equal to 10 while applying yearly growth; that would stretch across a full decade. Instead, think differently: split the rate in half, seeing as each phase adds only two percent instead of four. It might feel odd at first, yet keep one thing clear, whatever the count of stretches where money grows, the pace has to fit neatly into each single span. Examine how this unfolds in reality." }
      ,
      { tag: "h2", text: "Example" },
      { tag: "p", text: "Imagine using a setup like the earlier case. A thousand dollars goes into a bank account, only now the deal is four percent yearly interest, split into two payments every twelve months, lasting five calendar years. That gives six-month intervals where earnings are added back in each time. Figure out how much the starting sum becomes by the end of the fifth year. Interest comes every six months, so we split the yearly rate in two. That means each payment uses just part of the full annual percentage. Since payments happen twice a year, the total stretch of time doubles when counting cycles. A five-year span turns into ten moments when money grows. Begin with one thousand dollars, wait half a year, twenty bucks gets added at 2 percent. Now the amount climbs to one thousand twenty. When another six months pass, the bank applies 2 percent once more. But this time, it works on the larger sum from before. That gives you one thousand twenty dollars times one point zero two, which becomes one thousand forty and forty cents. Looked at over half a decade, the pattern appears clearly in the figure that follows." },
      { tag: "div", html: "<div class='panel'><table class='schedule-table'><thead><tr><th>Year</th><th>PV</th><th>Interest</th><th>FV</th></tr></thead><tbody><tr><td>0.5</td><td>$1,000.00</td><td>$20.00</td><td>$1,020.00</td></tr><tr><td>1</td><td>$1,020.00</td><td>$20.40</td><td>$1,040.40</td></tr><tr><td>1.5</td><td>$1,040.40</td><td>$20.81</td><td>$1,061.21</td></tr><tr><td>2</td><td>$1,061.21</td><td>$21.22</td><td>$1,082.43</td></tr><tr><td>2.5</td><td>$1,082.43</td><td>$21.65</td><td>$1,104.08</td></tr><tr><td>3</td><td>$1,104.08</td><td>$22.08</td><td>$1,126.16</td></tr><tr><td>3.5</td><td>$1,126.16</td><td>$22.52</td><td>$1,148.69</td></tr><tr><td>4</td><td>$1,148.69</td><td>$22.97</td><td>$1,171.66</td></tr><tr><td>4.5</td><td>$1,171.66</td><td>$23.43</td><td>$1,195.09</td></tr><tr><td>5</td><td>$1,195.09</td><td>$23.90</td><td>$1,218.99</td></tr></tbody></table></div>" },
      { tag: "p", text: "A bit more money shows up at the end compared to yearly compounding. Doing all this by hand takes many steps. Luckily, there is a way to find that amount using a formula instead. Pay close attention to each number you plug in. In this case, n means two times the total years, because it happens ten times over. Meanwhile, i becomes one-half of the yearly rate, due to splitting it across two periods every year. Below, you see how it plays out step by step." },
      { tag: "p", text: "Here's how it works: the formula gives a future amount, yet getting to interest takes just one more move. Take away the starting sum from that total, then you see what’s left. For instance, $1,218.99 drops down to $218.99 once you remove the original $1,000. That difference? It bundles every yearly interest chunk added up along the way." },
      { tag: "h2", text: "Ordinary Annuity" },
      { tag: "h2", text: "Annuity Due" },
      { tag: "h3", text: "Where:" },
      { tag: "p", html: "<ul><li><strong>FV</strong> = Future Value</li><li><strong>PMT</strong> = payment per period</li><li><strong>i</strong> = interest rate per period</li><li><strong>n</strong> = number of compounding periods</li></ul>" },
      { tag: "p", text: "Imagine putting one hundred thirty five dollars into a savings account every three months. The bank says it will give six percent interest, added four times per year. After the first few months, that initial money goes in and starts earning extra amounts over time. Each chunk of cash stays there, building up value with every passing quarter. By the third year's close, each deposit has grown through repeated compounding. Eleven cycles pass before the total sum appears on your statement. Think about how often the interest builds up, each little jump counts as one cycle. For three full years, interest adds in four separate moments every single year. But here’s the catch: when you put in $135 at the close of each quarter, the first batch grows over just eleven cycles, not twelve, simply because it didn’t start right at the beginning. Jump to the next quarter's end—you drop another $135 into the account. That newer chunk earns compound growth across ten rounds, not more. Each new payment follows this shrinking pattern. By the final moment after three years, you place the last $135 down. It sits untouched by interest, arriving exactly when you check what’s in the pot. Quarterly compounding means splitting the yearly rate into four parts. Each deposit gains interest every three months. Think of it as updating the balance four times a year. Visuals can help make sense of how this works over time." },
      { tag: "p", text: "Here comes another $135 every period. This sum grows through quarterly compounding, depending on how many quarters are left in the three years. Picture twelve separate growth runs, one each time money goes in. Each chunk gains interest until the full term ends. After thirty-six months pass, combine all those grown amounts for the final balance. See it unfold step by step in the lines below." },
      { tag: "div", html: "<div class='panel'><table class='schedule-table'><thead><tr><th>Year</th><th>Periods</th><th>PMT</th><th>Interest Factor</th><th>FV</th></tr></thead><tbody><tr><td>0.25</td><td>11</td><td>$135.0</td><td>1.1779489374</td><td>$159.023</td></tr><tr><td>0.5</td><td>10</td><td>$135.0</td><td>1.160540825</td><td>$156.673</td></tr><tr><td>0.75</td><td>9</td><td>$135.0</td><td>1.1433899754</td><td>$154.358</td></tr><tr><td>1</td><td>8</td><td>$135.0</td><td>1.1264925866</td><td>$152.076</td></tr><tr><td>1.25</td><td>7</td><td>$135.0</td><td>1.1098449129</td><td>$149.829</td></tr><tr><td>1.5</td><td>6</td><td>$135.0</td><td>1.0934432639</td><td>$147.615</td></tr><tr><td>1.75</td><td>5</td><td>$135.0</td><td>1.0772840039</td><td>$145.433</td></tr><tr><td>2</td><td>4</td><td>$135.0</td><td>1.0613635506</td><td>$143.284</td></tr><tr><td>2.25</td><td>3</td><td>$135.0</td><td>1.045678375</td><td>$141.167</td></tr><tr><td>2.5</td><td>2</td><td>$135.0</td><td>1.030225</td><td>$139.080</td></tr><tr><td>2.75</td><td>1</td><td>$135.0</td><td>1.015</td><td>$137.025</td></tr><tr><td>3</td><td>0</td><td>$135.0</td><td>1</td><td>$135.000</td></tr></tbody></table><div style='margin-top:8px'><strong>Total: $1,760.56</strong></div></div>" },
      { tag: "p", text: "We take the payment per period and multiply it by the part of the compound interest equation called the \"Interest Factor.\" Using that, we work out what each payment will be worth later on. Each amount grows separately over time. Then those grown amounts are added together for a total at year three. Sure, doing it step by step takes effort. But there's good news - a shortcut exists. One clean formula gives the same result faster. It uses only simple math. See how it works beneath this explanation." },
      { tag: "p", text: "Just like before, figuring out the interest means taking away the actual money put in every time. That adds up to 135 times 12, giving 1620 dollars. So the amount built through interest comes to 1760.56 minus 1620, landing at 140.56" },
      { tag: "h2", text: "Annuity Due" },
      { tag: "p", text: "Picture an annuity due. Here, things start a bit earlier. Imagine putting away 135 dollars every quarter for three full years. The account grows at six percent, compounded regularly. You\u2019re curious what shows up after those twelve quarters. What shifts now is timing - deposits land at the start of each stretch. Because of that small change, every payment rides through an extra round of growth. Right away, you put in $135 - so it grows across every one of the twelve phases. Instead of sitting idle, each dollar gains value step by step. Your final contribution, also $135, enters late but still picks up earnings once. Look at the image underneath - it shows just how that plays out." },
      { tag: "p", text: "Twelve payments show up again here. Each deposit earns interest during an extra phase compared to end-of-period timing. That explains the added twist in the Annuity Due equation - future worth gets bumped once more through compounding. Step by step, a dozen future amounts take shape. Add them together, result lands at year three's finish line. See how it unfolds in the lines of the chart just beneath." },
      { tag: "div", html: "<div class='panel'><table class='schedule-table'><thead><tr><th>Year</th><th>Periods</th><th>PMT</th><th>Interest Factor</th><th>FV</th></tr></thead><tbody><tr><td>0.25</td><td>12</td><td>$135.0</td><td>1.1956181715</td><td>$161.408</td></tr><tr><td>0.5</td><td>11</td><td>$135.0</td><td>1.1779489374</td><td>$159.023</td></tr><tr><td>0.75</td><td>10</td><td>$135.0</td><td>1.160540825</td><td>$156.673</td></tr><tr><td>1</td><td>9</td><td>$135.0</td><td>1.1433899754</td><td>$154.358</td></tr><tr><td>1.25</td><td>8</td><td>$135.0</td><td>1.1264925866</td><td>$152.076</td></tr><tr><td>1.5</td><td>7</td><td>$135.0</td><td>1.1098449129</td><td>$149.829</td></tr><tr><td>1.75</td><td>6</td><td>$135.0</td><td>1.0934432639</td><td>$147.615</td></tr><tr><td>2</td><td>5</td><td>$135.0</td><td>1.0772840039</td><td>$145.433</td></tr><tr><td>2.25</td><td>4</td><td>$135.0</td><td>1.0613635506</td><td>$143.284</td></tr><tr><td>2.5</td><td>3</td><td>$135.0</td><td>1.045678375</td><td>$141.167</td></tr><tr><td>2.75</td><td>2</td><td>$135.0</td><td>1.030225</td><td>$139.080</td></tr><tr><td>3</td><td>1</td><td>$135.0</td><td>1.015</td><td>$137.025</td></tr></tbody></table><div style='margin-top:8px'><strong>Total: $1,786.97</strong></div></div>" },
      { tag: "p", text: "Here's something to see - putting money in earlier means it grows a bit more, because every payment gets an extra round of interest. Doing this step by step takes just as much effort as the last way, yet there's good news: we still have that reliable equation ready. You'll find how it works written out next" },
      { tag: "p", text: "After three years, the amount reaches $1,786.97. To find the interest built up, take away the total deposited - still $1,620. That leaves $166.97 earned purely from interest." }
    ]
  };
})();
